root = "."           # Project root directory
tmp_dir = "tmp"      # Temporary directory for build outputs

[build]
# Command to build your application
cmd = "go build -o ./tmp/main.exe ./cmd/main.go"

# Output binary name
bin = "tmp/main.exe"

# Full path to binary
full_bin = ".\\tmp\\main.exe"

# File extensions to watch
include_ext = ["go", "tpl", "tmpl", "html"]

# Directories to exclude from watching
exclude_dir = ["assets", "tmp", "vendor"]

# Directories to specifically include (empty means all)
include_dir = []

# Files to exclude
exclude_file = []

# Delay in milliseconds between rebuilds
delay = 1000

# Stop on build errors
stop_on_error = true

# Log file for build errors
log = "air_errors.log"

[log]
time = true    # Include timestamps in logs

[color]
main = "yellow"     # Color for main messages
watcher = "cyan"    # Color for file watcher messages
build = "green"     # Color for build success messages
runner = "magenta"  # Color for runner messages

[misc]
clean_on_exit = true    # Clean temporary files when exiting